// This file is automatically generated by codeviewer_cli.
// Do not edit this file.

// Copyright 2019 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'code_style.dart';

class CodeSegments {
  static TextSpan axis(BuildContext context) {
    final codeStyle = CodeStyle.of(context);
    return TextSpan(children: [
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
      TextSpan(style: codeStyle.classStyle, text: 'Ruler'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'count'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.numberStyle, text: '1'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'cm'),
      TextSpan(style: codeStyle.punctuationStyle, text: ','),
      TextSpan(style: codeStyle.baseStyle, text: ' axis'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.classStyle, text: 'Axis'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'vertical'),
      TextSpan(style: codeStyle.punctuationStyle, text: ')'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
    ]);
  }

  static TextSpan count(BuildContext context) {
    final codeStyle = CodeStyle.of(context);
    return TextSpan(children: [
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
      TextSpan(style: codeStyle.classStyle, text: 'Ruler'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'count'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.numberStyle, text: '3'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'cm'),
      TextSpan(style: codeStyle.punctuationStyle, text: '),'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
    ]);
  }

  static TextSpan doubleSided(BuildContext context) {
    final codeStyle = CodeStyle.of(context);
    return TextSpan(children: [
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
      TextSpan(style: codeStyle.classStyle, text: 'DynamicDoubleSidedRuler'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a      cmWidth'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.numberStyle, text: '100'),
      TextSpan(style: codeStyle.punctuationStyle, text: ','),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a      child'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.classStyle, text: 'Container'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.baseStyle, text: 'color'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.classStyle, text: 'Colors'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'red'),
      TextSpan(style: codeStyle.punctuationStyle, text: ','),
      TextSpan(style: codeStyle.baseStyle, text: ' height'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.numberStyle, text: '100'),
      TextSpan(style: codeStyle.punctuationStyle, text: ','),
      TextSpan(style: codeStyle.baseStyle, text: ' width'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.numberStyle, text: '100'),
      TextSpan(style: codeStyle.punctuationStyle, text: '),'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a    '),
      TextSpan(style: codeStyle.punctuationStyle, text: ');'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
    ]);
  }

  static TextSpan dynamic(BuildContext context) {
    final codeStyle = CodeStyle.of(context);
    return TextSpan(children: [
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
      TextSpan(style: codeStyle.classStyle, text: 'Ruler'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.keywordStyle, text: 'dynamic'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.numberStyle, text: '300'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'cm'),
      TextSpan(style: codeStyle.punctuationStyle, text: ')'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
    ]);
  }

  static TextSpan notchColor(BuildContext context) {
    final codeStyle = CodeStyle.of(context);
    return TextSpan(children: [
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
      TextSpan(style: codeStyle.classStyle, text: 'Ruler'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'count'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.numberStyle, text: '1'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'cm'),
      TextSpan(style: codeStyle.punctuationStyle, text: ','),
      TextSpan(style: codeStyle.baseStyle, text: ' notchColor'),
      TextSpan(style: codeStyle.punctuationStyle, text: ':'),
      TextSpan(style: codeStyle.baseStyle, text: ' '),
      TextSpan(style: codeStyle.classStyle, text: 'Colors'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'black'),
      TextSpan(style: codeStyle.punctuationStyle, text: ')'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
    ]);
  }

  static TextSpan real(BuildContext context) {
    final codeStyle = CodeStyle.of(context);
    return TextSpan(children: [
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
      TextSpan(style: codeStyle.classStyle, text: 'Ruler'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'count'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.numberStyle, text: '1'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'cm'),
      TextSpan(style: codeStyle.punctuationStyle, text: ')'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
    ]);
  }

  static TextSpan rulerCount(BuildContext context) {
    final codeStyle = CodeStyle.of(context);
    return TextSpan(children: [
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
      TextSpan(style: codeStyle.classStyle, text: 'Ruler'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'count'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.numberStyle, text: '10'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'cm'),
      TextSpan(style: codeStyle.punctuationStyle, text: '),'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
    ]);
  }

  static TextSpan rulerDynamic(BuildContext context) {
    final codeStyle = CodeStyle.of(context);
    return TextSpan(children: [
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
      TextSpan(style: codeStyle.classStyle, text: 'Ruler'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.keywordStyle, text: 'dynamic'),
      TextSpan(style: codeStyle.punctuationStyle, text: '('),
      TextSpan(style: codeStyle.numberStyle, text: '300'),
      TextSpan(style: codeStyle.punctuationStyle, text: '.'),
      TextSpan(style: codeStyle.baseStyle, text: 'cm'),
      TextSpan(style: codeStyle.punctuationStyle, text: '),'),
      TextSpan(style: codeStyle.baseStyle, text: '\u000a\u000a'),
    ]);
  }
}
